RI-1418: Improve code readability

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -20,9 +20,9 @@ on:
       - master
 
 env:
-  DEPOT_BINARY_VERSION: "${{ inputs.binary_version || 'v6.6.41' }}"
-  DEPOT_REPOSITORY_ORG: "${{ inputs.repository_org  || 'ComposableFi' }}"
-  DEPOT_REPOSITORY_NAME: "${{ inputs.repository_name || 'composable-cosmos'}}"
+  DEPOT_BINARY_VERSION: "${{ inputs.binary_version || 'v0.2.0' }}"
+  DEPOT_REPOSITORY_ORG: "${{ inputs.repository_org  || 'babylonchain' }}"
+  DEPOT_REPOSITORY_NAME: "${{ inputs.repository_name || 'finality-provider'}}"
   DEPOT_BUCKET_NAME: "depot"
   DEPOT_BUCKET_PUBLIC_URL: "https://depot.r2.restake.cloud"
   SLACK_BOT_TOKEN: "${{ secrets.SLACK_BOT_TOKEN }}"
@@ -37,8 +37,8 @@ jobs:
       depot_purpose: "${{ steps.set-outputs.outputs.depot_purpose }}"
       depot_project_name: "${{ steps.set-outputs.outputs.depot_project_name }}"
       depot_automatic_builds: "${{ steps.set-outputs.outputs.depot_automatic_builds }}"
-      depot_image_builds: "${{ steps.set-outputs.outputs.depot_image_builds }}"
-      depot_docker_image_binaries: "${{ steps.set-outputs.outputs.depot_docker_image_binaries }}"
+      depot_docker_builds: "${{ steps.set-outputs.outputs.depot_docker_builds }}"
+      depot_docker_binaries: "${{ steps.set-outputs.outputs.depot_docker_binaries }}"
     steps:
       - id: "checkout"
         name: "Checkout code"
@@ -58,10 +58,10 @@ jobs:
         name: "Set outputs to use in other jobs"
         run: |
           echo "depot_automatic_builds=${{ env.DEPOT_AUTOMATIC_BUILDS }}" >> $GITHUB_OUTPUT
-          echo "depot_image_builds=${{ env.DEPOT_IMAGE_BUILDS }}" >> $GITHUB_OUTPUT
+          echo "depot_docker_builds=${{ env.DEPOT_DOCKER_BUILDS }}" >> $GITHUB_OUTPUT
           echo "depot_purpose=${{ env.DEPOT_PURPOSE }}" >> $GITHUB_OUTPUT
           echo "depot_project_name=${{ env.DEPOT_PROJECT_NAME }}" >> $GITHUB_OUTPUT
-          echo "depot_docker_image_binaries=${{ env.DEPOT_DOCKER_IMAGE_BINARIES }}" >> $GITHUB_OUTPUT
+          echo "depot_docker_binaries=${{ env.DEPOT_DOCKER_BINARIES }}" >> $GITHUB_OUTPUT
           printf "depot_binaries=%s" "${DEPOT_BINARIES//$'\n'/\\n}" >> $GITHUB_OUTPUT
 
       - id: "early-exit"
@@ -127,71 +127,74 @@ jobs:
           if-no-files-found: "error"
           retention-days: 1
 
-  # upload:
-  #   name: "Upload"
-  #   needs: "build"
-  #   runs-on: "ubuntu-latest"
-  #   if: ${{ needs.build.outputs.depot_automatic_builds == 'true' }}
-  #   steps:
-  #     - id: "checkout"
-  #       name: "Checkout code"
-  #       uses: actions/checkout@v4
-
-  #     - id: "download-artifacts"
-  #       name: "Download binaries from workspace"
-  #       uses: "actions/download-artifact@v4"
-  #       with:
-  #         name: "binaries"
-  #         path: "binaries"
-
-  #     - id: "setup-rclone"
-  #       name: "Set up rclone CLI"
-  #       run: curl https://rclone.org/install.sh | sudo bash
-
-  #     - id: "setup-rclone-config"
-  #       name: "Set up rclone config"
-  #       run: printf "%s" "${{ secrets.R2_CONFIG }}" > rclone.conf
-
-  #     - id: "upload-binary"
-  #       name: "Upload binary to R2 bucket and verify a successful upload"
-  #       run: |
-  #         set -euo pipefail
-
-  #         for file in binaries/*; do
-  #           if [ -f "$file" ]; then
-  #             filename=$(basename "$file")
-  #             directory="${{ needs.build.outputs.depot_purpose }}/${{ needs.build.outputs.depot_project_name }}/${{ env.DEPOT_BINARY_VERSION }}"
-
-  #             rclone --config="rclone.conf" copy "$file" "r2:${{ env.DEPOT_BUCKET_NAME }}/${directory}"
-
-  #             status_code=$(curl -sL -w "%{http_code}\\n" "${{ env.DEPOT_BUCKET_PUBLIC_URL }}/${directory}/${filename}" -o /dev/null)
-  #             if [ "$status_code" -ne 200 ]; then
-  #               echo "Error: Binary $filename is not downloadable (HTTP status code $status_code)"
-  #               exit 1
-  #             fi
-  #           fi
-  #         done
-
-  build-docker:
-    runs-on: ubuntu-latest
-    needs: ["build"]
-    if: ${{ needs.build.outputs.depot_image_builds == 'true' && needs.build.result == 'success' }}
-    outputs:
-      build-status: "${{ needs.build.result }}"
-      image-names: "${{ needs.build.outputs.depot_docker_image_binaries }}"
-      image-builds: "${{ needs.build.outputs.depot_image_builds }}"
+  upload:
+    name: "Upload"
+    needs: "build"
+    runs-on: "ubuntu-latest"
+    if: ${{ needs.build.outputs.depot_automatic_builds == 'true' }}
     steps:
-      - name: "Checkout repository"
+      - id: "checkout"
+        name: "Checkout code"
         uses: actions/checkout@v4
 
-      - name: "Download binary artifact"
+      - id: "download-artifacts"
+        name: "Download binaries from workspace"
+        uses: "actions/download-artifact@v4"
+        with:
+          name: "binaries"
+          path: "binaries"
+
+      - id: "setup-rclone"
+        name: "Set up rclone CLI"
+        run: curl https://rclone.org/install.sh | sudo bash
+
+      - id: "setup-rclone-config"
+        name: "Set up rclone config"
+        run: printf "%s" "${{ secrets.R2_CONFIG }}" > rclone.conf
+
+      - id: "upload-binary"
+        name: "Upload binary to R2 bucket and verify a successful upload"
+        run: |
+          set -euo pipefail
+
+          for file in binaries/*; do
+            if [ -f "$file" ]; then
+              filename=$(basename "$file")
+              directory="${{ needs.build.outputs.depot_purpose }}/${{ needs.build.outputs.depot_project_name }}/${{ env.DEPOT_BINARY_VERSION }}"
+
+              rclone --config="rclone.conf" copy "$file" "r2:${{ env.DEPOT_BUCKET_NAME }}/${directory}"
+
+              status_code=$(curl -sL -w "%{http_code}\\n" "${{ env.DEPOT_BUCKET_PUBLIC_URL }}/${directory}/${filename}" -o /dev/null)
+              if [ "$status_code" -ne 200 ]; then
+                echo "Error: Binary $filename is not downloadable (HTTP status code $status_code)"
+                exit 1
+              fi
+            fi
+          done
+
+  docker:
+    name: "Build and Publish Docker"
+    runs-on: "ubuntu-latest"
+    needs: ["build"]
+    if: ${{ needs.build.outputs.depot_docker_builds == 'true' && needs.build.result == 'success' }}
+    outputs:
+      build-status: "${{ needs.build.result }}"
+      image-names: "${{ needs.build.outputs.depot_docker_binaries }}"
+      image-builds: "${{ needs.build.outputs.depot_docker_builds }}"
+    steps:
+      - id: "checkout"
+        name: "Checkout repository"
+        uses: actions/checkout@v4
+
+      - id: "download-binaries"
+        name: "Download binaries artifact"
         uses: actions/download-artifact@v4
 
-      - id: "set_env"
-        name: "Set env variables"
+      - id: "set-docker-env"
+        name: "Set environment variables for Docker"
         run: |
           echo "DEPOT_PROJECT_NAME=${{ needs.build.outputs.depot_project_name }}" >> "${GITHUB_ENV}"
-          echo "DEPOT_DOCKER_IMAGE_BINARIES=${{ needs.build.outputs.depot_docker_image_binaries }}" >> "${GITHUB_ENV}"
+          echo "DEPOT_DOCKER_BINARIES=${{ needs.build.outputs.depot_docker_binaries }}" >> "${GITHUB_ENV}"
 
       - id: "login-ghcr"
         name: "Log in to the Container registry"
@@ -201,49 +204,50 @@ jobs:
           username: "restake-bot"
           password: "${{ secrets.RESTAKE_BOT_TOKEN }}"
 
-      - name: Build and push Docker image
+      - id: "build-docker"
+        name: "Build and push Docker image"
         uses: docker/build-push-action@v5
         with:
           context: .
           file: "templates/Dockerfile"
-          platforms: linux/amd64
+          platforms: "linux/amd64"
           push: true
           no-cache: true
           tags: |
-            ghcr.io/restake/${{env.DEPOT_PROJECT_NAME}}:${{env.DEPOT_BINARY_VERSION}}
+            ghcr.io/restake/depot/${{ env.DEPOT_PROJECT_NAME }}:${{ env.DEPOT_BINARY_VERSION }}
 
-  # notify:
-  #   name: "Notify on Slack"
-  #   runs-on: "ubuntu-latest"
-  #   needs: ["build", "upload"]
-  #   if: ${{ needs.build.outputs.depot_automatic_builds == 'true' && needs.build.result == 'success' || needs.upload.result == 'success' || needs.build.result != 'success' || needs.upload.result != 'success' }}
-  #   outputs:
-  #     build-status: "${{ needs.build.result }}"
-  #     upload-status: "${{ needs.upload.result }}"
-  #   steps:
-  #     - id: "get-workflow-url"
-  #       name: "Get workflow URL"
-  #       run: |
-  #         workflow_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
-  #         echo "WORKFLOW_URL=${workflow_url}" >> "${GITHUB_ENV}"
-  #         echo "DEPOT_BINARY_NAMES=${{ needs.build.outputs.depot_binaries }}" >> "${GITHUB_ENV}"
+  notify:
+    name: "Notify on Slack"
+    runs-on: "ubuntu-latest"
+    needs: ["build", "upload"]
+    if: ${{ needs.build.outputs.depot_automatic_builds == 'true' && needs.build.result == 'success' || needs.upload.result == 'success' || needs.build.result != 'success' || needs.upload.result != 'success' }}
+    outputs:
+      build-status: "${{ needs.build.result }}"
+      upload-status: "${{ needs.upload.result }}"
+    steps:
+      - id: "get-workflow-url"
+        name: "Get workflow URL"
+        run: |
+          workflow_url="${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"
+          echo "WORKFLOW_URL=${workflow_url}" >> "${GITHUB_ENV}"
+          echo "DEPOT_BINARY_NAMES=${{ needs.build.outputs.depot_binaries }}" >> "${GITHUB_ENV}"
 
-  #     - id: "checkout"
-  #       name: "Checkout code"
-  #       uses: actions/checkout@v4
+      - id: "checkout"
+        name: "Checkout code"
+        uses: actions/checkout@v4
 
-  #     - id: "slack-notify-failure"
-  #       name: "Notify on Slack upon failure"
-  #       if: "${{ needs.build.result != 'success' || needs.upload.result != 'success' }}"
-  #       uses: slackapi/slack-github-action@v1.25.0
-  #       with:
-  #         channel-id: "${{ env.SLACK_CHANNEL_ID }}"
-  #         payload-file-path: "./templates/notify-failure.json"
+      - id: "slack-notify-failure"
+        name: "Notify on Slack upon failure"
+        if: "${{ needs.build.result != 'success' || needs.upload.result != 'success' }}"
+        uses: slackapi/slack-github-action@v1.25.0
+        with:
+          channel-id: "${{ env.SLACK_CHANNEL_ID }}"
+          payload-file-path: "./templates/notify-failure.json"
 
-  #     - id: "slack-notify-success"
-  #       name: "Notify on Slack upon success"
-  #       if: "${{ needs.build.result == 'success' && needs.upload.result == 'success' }}"
-  #       uses: slackapi/slack-github-action@v1.25.0
-  #       with:
-  #         channel-id: "${{ env.SLACK_CHANNEL_ID }}"
-  #         payload-file-path: "./templates/notify-success.json"
+      - id: "slack-notify-success"
+        name: "Notify on Slack upon success"
+        if: "${{ needs.build.result == 'success' && needs.upload.result == 'success' }}"
+        uses: slackapi/slack-github-action@v1.25.0
+        with:
+          channel-id: "${{ env.SLACK_CHANNEL_ID }}"
+          payload-file-path: "./templates/notify-success.json"
